export const XiboSnippetVersion = '0.0.24'

export * from './Xibo'
// export * from './XiboCampaign'
// export * from './XiboDisplayGroups'
export * from './XiboDisplays'
// export * from './XiboLayout'
// export * from './XiboMedia'
// export * from './XiboPlaylist'
// export * from './XiboRegion'
// export * from './XiboSchedules'
export * from './XiboTags'
// export * from './XiboUser'
// export * from './XiboUserGroup'
// export * from './XiboWidgets'
// export * from './testing/XiboApp'